id: prometheus

info:
  name: Prometheus Scan
  author: internal
  description: |
    Service-specific scan for prometheus. Covers: fingerprint detection, security exposure checks.
  tags: workflow,prometheus

workflows:
  - template: RBKD-templates/http/technologies/prometheus-detect.yaml
  - template: RBKD-templates/http/exposures/prometheus-metrics-exposed.yaml
