id: prometheus

info:
  name: Prometheus Scan
  author: internal
  description: |
    Service-specific scan for prometheus. Covers: fingerprint detection, security exposure checks.
  tags: workflow,prometheus

workflows:
  - template: http/exposed-panels/prometheus-exposed-panel.yaml
    subtemplates:
      - template: http/exposures/configs/prometheus-metrics.yaml
      - template: http/misconfiguration/prometheus/prometheus-unauth.yaml
      - template: http/misconfiguration/prometheus/prometheus-config.yaml
      - template: http/misconfiguration/prometheus/prometheus-targets.yaml
